"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
class utf8reader:
    """Takes a utf8-encoded string reader and reads bytes out of it"""
    def __init__(self, str_reader) -> None:
        ...
    
    def read(self, n):
        ...
    


_str_vs_bytes_warning = ...
def bytes_reader(f):
    """Returns a file-like object that reads bytes"""
    ...

