"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
HEADERS = ...
def to_string(o):
    ...

def dump():
    ...

if __name__ == '__main__':
    ...
