"""
This type stub file was generated by pyright.
"""

import collections
from ijson import compat

"""
This type stub file was generated by pyright.
"""
class utf8reader_async(compat.utf8reader):
    """
    Takes a utf8-encoded string asynchronous reader and asynchronously reads
    bytes out of it
    """
    async def read(self, n):
        ...
    


class sendable_deque(collections.deque):
    '''Like utils.sendable_list, but for deque objects'''
    send = ...


class async_iterable:
    '''
    A utility class that implements an async iterator returning values
    dispatched by a coroutine pipeline after *it* has received values coming
    from an async file-like object.
    '''
    def __init__(self, f, buf_size, *coro_pipeline) -> None:
        ...
    
    def __aiter__(self):
        ...
    
    async def __anext__(self):
        ...
    


