"""
This type stub file was generated by pyright.
"""

import os
import warnings

"""
This type stub file was generated by pyright.
"""
class YAJLImportError(ImportError):
    ...


def require_version(version, required):
    '''
    Asserts that the major component of 'version' is equal to 'required'.
    Raises YAJLImportError otherwise.
    '''
    ...

def get_yajl_version(yajl):
    ...

def find_yajl_ctypes(required):
    '''
    Finds and loads yajl shared object of the required major
    version (1, 2, ...) using ctypes.
    '''
    ...

def find_yajl_cffi(ffi, required):
    '''
    Finds and loads yajl shared object of the required major
    version (1, 2, ...) using cffi.
    '''
    ...

